import React from 'react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './css/globals.css'
import { ShadcnThemeProvider } from '@/components/theme-provider'
import { ThemeProvider } from 'flowbite-react'
import customTheme from '@/utils/theme/custom-theme'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'MaterialM-Nextjs-Free',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en' suppressHydrationWarning>
      <head>
        <link rel='icon' href='/favicon.svg' type='image/svg+xml' />
        {/* {typeof window !== 'undefined' && <ThemeModeScript />} */}
      </head>
      <body className={`${inter.className}`}>
        <ShadcnThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange>
          <ThemeProvider theme={customTheme}>{children}</ThemeProvider>
        </ShadcnThemeProvider>
      </body>
    </html>
  )
}
