import Image from 'next/image'
import { Button } from "@/components/ui/button";
import Link from 'next/link'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Error-404',
  description: 'Generated by create next app',
}
const Error = () => {
  return (
    <>
      <div className='h-screen flex items-center justify-center bg-background'>
        <div className='text-center'>
          <Image
            src={'/images/backgrounds/errorimg.svg'}
            alt='error'
            className='mb-4'
            width={400}
            height={300}
          />
          <h1 className='text-ld text-4xl mb-6'>Opps!!!</h1>
          <h6 className='text-xl text-ld'>
            This page you are looking for could not be found.
          </h6>
          <Button
            asChild
            className="mt-6 mx-auto"
          >
            <Link href="/">
              Go Back to Home
            </Link>
          </Button>
        </div>
      </div>
    </>
  )
}

export default Error
